.github/workflows/nodejs.yml
README.md
package-lock.json
package.json
src/index.js
src/minify.js
test/CssnanoPlugin.test.js
test/__snapshots__/CssnanoPlugin.test.js.snap.webpack4
test/__snapshots__/CssnanoPlugin.test.js.snap.webpack5
test/__snapshots__/sourceMap-option.test.js.snap.webpack4
test/__snapshots__/sourceMap-option.test.js.snap.webpack5
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/__snapshots__/warningsFilter-option.test.js.snap.webpack4
test/__snapshots__/warningsFilter-option.test.js.snap.webpack5
test/__snapshots__/worker.test.js.snap.webpack4
test/__snapshots__/worker.test.js.snap.webpack5
test/warningsFilter-option.test.js
test/worker.test.js

Refactor code
Readmy edit
No
No

refactor: code

---

.gitignore
src/Webpack4Cache.js
src/Webpack5Cache.js
src/index.js
test/__snapshots__/cache-option.test.js.snap.webpack5
test/cache-option.test.js
test/helpers/getCompiler.js

avoid deprecation
Only for webpack@5
No

fix: compatibility with webpack@5

---

test/CssMinimizerPlugin.test.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack4
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack5
test/__snapshots__/sourceMap-option.test.js.snap.webpack4
test/__snapshots__/sourceMap-option.test.js.snap.webpack5
test/__snapshots__/test-option.test.js.snap.webpack4
test/__snapshots__/test-option.test.js.snap.webpack5
test/sourceMap-option.test.js
test/test-option.test.js

Test refactor

---

src/index.js
test/CssMinimizerPlugin.test.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack4
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack5

Improve stats output for webpack@5
No
No

feat: show minimized assets in stats for webpack@5

---

src/Webpack5Cache.js
src/index.js

refactor: migrate on processAssets hook

---

src/Webpack4Cache.js
src/Webpack5Cache.js
src/index.js
src/minify.js
test/CssMinimizerPlugin.test.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack4
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack5
test/__snapshots__/cache-option.test.js.snap.webpack4
test/__snapshots__/worker.test.js.snap.webpack4
test/__snapshots__/worker.test.js.snap.webpack5
test/cache-option.test.js
test/worker.test.js

cache sources for webpack@4, less memory on webpack@5
No
No

Fix compatibility with webpack 5

---

src/Webpack4Cache.js
src/Webpack5Cache.js
src/index.js
test/__snapshots__/sourceMap-option.test.js.snap.webpack4
test/__snapshots__/sourceMap-option.test.js.snap.webpack5
test/cache-option.test.js
test/sourceMap-option.test.js

Refactor code

---

README.md
src/minify.js
test/CssMinimizerPlugin.test.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack4
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack5
test/sourceMap-option.test.js
test/warningsFilter-option.test.js

Refactor minify option
Yes
Change signature `minify` option
No

Refactor minify option

---

test/CssMinimizerPlugin.test.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack4
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack5
test/fixtures/simple.js

test: cache on webpack@5

---

README.md

Simply correcting an out-dated (or maybe a typo) link
No breaking changes

docs(readme): Correcting optimisations link

---

package-lock.json
package.json
test/CssMinimizerPlugin.test.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack5

Updated `mini-css-extract-plugin` and test cache for webpack@5
No
No

test: updated mini-css-extract-plugin and test cache for webpack@5

---

package-lock.json
package.json
src/index.js

Chore: updated schema-utils

---

test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack5

Updated snapshot with hashes
No
No

test: updated snapshot with hashes

---

README.md
package-lock.json
package.json
src/minify.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack5
test/__snapshots__/cssMinimizerOptions-option.test.js.snap.webpack4
test/__snapshots__/cssMinimizerOptions-option.test.js.snap.webpack5
test/cssMinimizerOptions-option.test.js
test/fixtures/sss/index.sss
test/fixtures/sugarss.js
test/worker.test.js

Feat: added support processorOptions

---

README.md
src/index.js
src/minify.js
test/__snapshots__/minify-option.test.js.snap
test/minify-option.test.js

Refactor perf

---

README.md
package-lock.json
package.json
test/__snapshots__/minimizerOptions-option.test.js.snap
test/fixtures/minimizerOptions/order.css
test/minimizerOptions-option.test.js

docs: update

---

.github/workflows/nodejs.yml
babel.config.js
package-lock.json
package.json

Node 10 dropped
Node 10 dropped
No

chore(deps): node 10 dropped

---

README.md

Fixes #90
Confusion described in #90 
None

Clarify wording about optimization.minimize true

---

README.md

Fix for the readme getting started code
none
I'm unsure why this would have happened, as I've not been following the development of webpack very closely.

change `loaders` to `rules` in README

---

src/options.json
test/__snapshots__/validate-options.test.js.snap

Use GitHub links instead of `webpack.js.org`
None
No

refactor: use github links

---

lint-staged.config.js

`lint-staged.config` updated
No
No

chore: lint-staged.config updated

---

package-lock.json

I ran into a couple of security warnings related to `cssnano` and subsequent transitive dependencies. Luckily, an `npm audit fix` seems to resolve those.

Resolve security concerns in cssnano dependency tree

---

package-lock.json
test/__snapshots__/CssMinimizerPlugin.test.js.snap

update deps and tests
No
Before starting fixes

chore(deps): update

---

src/index.js
src/minify.js
src/utils.js
test/CssMinimizerPlugin.test.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap
test/__snapshots__/cache-option.test.js.snap
test/__snapshots__/minify-option.test.js.snap
test/__snapshots__/sourceMap-option.test.js.snap
test/__snapshots__/warningsFilter-option.test.js.snap
test/__snapshots__/worker.test.js.snap
test/minify-option.test.js
test/sourceMap-option.test.js
test/worker.test.js

fix source map generation for multiple minify functions + improve perf
No
No

Fix source map generation for multiple minify functions

---

src/utils.js

Just fixes the comment
None
Relevant discussion: https://github.com/webpack-contrib/css-minimizer-webpack-plugin/commit/987d45402af81d88fbd1489021f8d14e5ff26a74#r57485732

chore: Fix inacurate code comment for ESBuild

---

src/index.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap
test/__snapshots__/cache-option.test.js.snap
test/__snapshots__/minify-option.test.js.snap
test/__snapshots__/sourceMap-option.test.js.snap
test/__snapshots__/warningsFilter-option.test.js.snap

to align with other minimizer plugins
No
No

refactor: error/warning message

---

package-lock.json
src/minify.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap
test/__snapshots__/minify-option.test.js.snap
test/minify-option.test.js

fix: minified result can be empty

---

.github/workflows/nodejs.yml
test/CssMinimizerPlugin.test.js

ci: added node.js 17

---

test/CssMinimizerPlugin.test.js
test/__snapshots__/sourceMap-option.test.js.snap
test/cache-option.test.js
test/sourceMap-option.test.js
test/warningsFilter-option.test.js

refactor test and avoid using deprecation methods
No
No

Test refactor deprecation

---

README.md
package-lock.json
package.json
src/index.js
src/minify.js
src/utils.js
test/CssMinimizerPlugin.test.js
test/__snapshots__/CssMinimizerPlugin.test.js.snap
test/__snapshots__/minify-option.test.js.snap
test/__snapshots__/worker.test.js.snap
test/worker.test.js
tsconfig.json
types/cjs.d.ts
types/index.d.ts
types/minify.d.ts
types/utils.d.ts

added types + setup types validation, fixes https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/141
No
No

feat: added types

---

README.md

fix: change loaders to rules

---

README.md
package-lock.json
package.json
src/index.js
src/utils.js
test/__snapshots__/minify-option.test.js.snap
test/fixtures/nesting.css
test/minify-option.test.js

fixes #153
No
- prefixes are broken and do not work
- minification is broken for special IE10/11 properties (i.e. `*prop: value`)
- collapsing properties are broken in some cases
- escaped things are broken

feat: added `@parcel/css` support

---

README.md
package-lock.json
package.json
src/index.js
src/utils.js
test/__snapshots__/minify-option.test.js.snap
test/minify-option.test.js
types/index.d.ts
types/utils.d.ts

feat: added `swc` minimizer

---

package-lock.json
package.json
src/utils.js

fix: handle `swc` errors

---

package-lock.json
package.json
src/utils.js

refactor: fix types

---

README.md

Fix link to cssnano

---

.github/workflows/nodejs.yml
package-lock.json

ci: add node v24
