- src/index.js
- src/options.json
- test/__snapshots__/validate-options.test.js.snap
- test/validate-options.test.js
add validate options schema
- not support unknown options
No
> refactor: add validate options schema

- package-lock.json
- package.json
- src/index.js
> refactor: code

- package-lock.json
- package.json
- src/Webpack4Cache.js
- src/Webpack5Cache.js
- src/index.js
- src/minify.js
- src/options.json
- test/CssNano.test.js
- test/__snapshots__/validate-options.test.js.snap
- test/cssnanoOptions-option.test.js
- test/helpers/getCacheDirectory.js
- test/helpers/index.js
- test/helpers/removeCache.js
- test/sourceMap-option.test.js
- test/test-option.test.js
- test/validate-options.test.js
add cache and multi-process parallel running
No
No
> feat: add cache and parallel

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/BUG.md
- .github/ISSUE_TEMPLATE/FEATURE.md
- .github/ISSUE_TEMPLATE/MODIFICATION.md
- .github/workflows/nodejs.yml
- README.md
- package-lock.json
- package.json
- src/minify.js
> refactor: before release

- jest.config.js
- setupTest.js
- test/CssMinimizerPlugin.test.js
- test/cache-option.test.js
- test/cssMinimizerOptions-option.test.js
- test/parallel-option.test.js
- test/sourceMap-option.test.js
- test/test-option.test.js
> test: increase timeout

- src/Webpack5Cache.js
- src/index.js
- src/minify.js
- test/CssMinimizerPlugin.test.js
- test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack4
- test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack5
- test/helpers/preLoader.js
- test/worker.test.js
Avoid double compression using child compilations
No
No
> fix: skip double compression for child compilation

- README.md
> doc: add missing import

- README.md
Comment regarding use of spread operator to extend existing minimizers lacked a comma causing syntax errors
To prevent future noobs from struggling with extending existing minimizers, I have added a comma to the comment.
> Add missing comma to comment

- src/index.js
- test/CssMinimizerPlugin.test.js
- test/__snapshots__/CssMinimizerPlugin.test.js.snap.webpack5
- test/helpers/EmitNewAsset.js
- test/helpers/index.js
Run optimize against assets added later by plugins for webpack@5
No
No
> feat: run optimize against assets added later by plugins for webpack@5

- src/minify.js
- test/__snapshots__/sourceMap-option.test.js.snap.webpack4
- test/__snapshots__/sourceMap-option.test.js.snap.webpack5
- test/__snapshots__/worker.test.js.snap.webpack4
- test/__snapshots__/worker.test.js.snap.webpack5
- test/sourceMap-option.test.js
> fix: crash with source maps when the `parallel` option is `false`

- README.md
- package-lock.json
- package.json
- src/index.js
- src/minify.js
- src/options.json
- src/utils.js
- test/CssMinimizerPlugin.test.js
- test/__snapshots__/CssMinimizerPlugin.test.js.snap
- test/__snapshots__/minify-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/minify-option.test.js
- test/validate-options.test.js
- test/worker.test.js
added the ability to pass an array of functions to the minify option
No
No
> Feat: added the ability to pass an array of functions to the minify option

- README.md
- src/minify.js
- test/CssMinimizerPlugin.test.js
- test/cache-option.test.js
- test/minify-option.test.js
- test/warningsFilter-option.test.js
- test/worker.test.js
Previously, the `minifi` function returned the css result as a key `code` or `css`.
Now - only in the key of `code`.
Yes
No
> Refactor: dropped support `css` key from output `minify` function

- README.md
- package-lock.json
- package.json
- src/index.js
- src/utils.js
- test/__snapshots__/minify-option.test.js.snap
- test/minify-option.test.js
- test/worker.test.js
> Feat: added defaults functions for `clean-css` and `csso`

- package-lock.json
- package.json
- test/__snapshots__/CssMinimizerPlugin.test.js.snap
Update cssnano from 4.1.10 to 4.1.11 because it had a dependency (is-svg) with a security issue (https://github.com/cssnano/cssnano/issues/1025). They've got rid of that in the 4.1.11 release.
- [ x] **bugfix**
- [x ] **test update** 
Remove a security vulnerability.
Hi! 👋
> build: update cssnano to 4.1.11

- README.md
- src/index.js
- src/minify.js
- test/__snapshots__/CssMinimizerPlugin.test.js.snap
- test/__snapshots__/cache-option.test.js.snap
- test/__snapshots__/minify-option.test.js.snap
- test/__snapshots__/sourceMap-option.test.js.snap
- test/__snapshots__/warningsFilter-option.test.js.snap
- test/minify-option.test.js
allow to return errors + improve formatting them 
No
No
> feat: allow returning errors from custom minimize function

- README.md
- package-lock.json
- package.json
- src/index.js
- src/utils.js
- test/__snapshots__/minify-option.test.js.snap
- test/minify-option.test.js
added `esbuild` minimizer for CSS
No
No
> feat: added `esbuild` minimizer

- src/utils.js
- test/__snapshots__/minify-option.test.js.snap
- test/__snapshots__/sourceMap-option.test.js.snap
- test/minify-option.test.js
> fix: source map generation for cssnano

- package.json
- src/cjs.js
- src/index.js
- src/minify.js
- src/utils.js
- test/cache-option.test.js
- test/cjs.test.js
- types/cjs.d.ts
- types/index.d.ts
removed cjs wrapper and generated types in commonjs format (`export =` and `namespaces` used in types), now you can directly use exported types
Potentially yes, but we use `babel` and our format is commonjs, but types in ESM, it is bug, also now you can reuse our types 
No
> feat: removed cjs wrapper and generated types in commonjs format

- package-lock.json
- package.json
- src/index.js
- src/utils.js
- types/index.d.ts
- types/utils.d.ts
> fix: cssnano types

- .cspell.json
- .github/workflows/nodejs.yml
- lint-staged.config.js
- package-lock.json
- package.json
- test/__snapshots__/minify-option.test.js.snap
- test/__snapshots__/minimizerOptions-option.test.js.snap
use the latest cssnano version
Yes - https://github.com/cssnano/cssnano/releases/tag/cssnano%406.0.0
No
> feat: update `cssnano` to v6

- README.md
Fix cssnano optimisations link broken
AS IS
https://cssnano.co/docs/what-are-optimisations/
TO BE
https://cssnano.github.io/cssnano/docs/what-are-optimisations/
> docs: fix cssnano optimisations link broken

- README.md
- src/index.js
- src/utils.js
- test/__snapshots__/parallel-option.test.js.snap
- test/parallel-option.test.js
- types/index.d.ts
- types/utils.d.ts
use os.availableParallelism() for parallelism when it is available
No
No
> fix: use os.availableParallelism() for parallelism when it is available

- src/index.js
- src/utils.js
- test/minify-option.test.js
- types/index.d.ts
- types/utils.d.ts
> fix: better types
